---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd lib/lambda
        npm install
    - run: |
        npm install
        npm run build
        npm run test
